---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes


  - name: install apache2 package
    yum:
      name: httpd
      state: latest
  
  - name: install php support for apache
    yum:
      name: php
      state: latest
