---





- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache updates (CentOS)
    tags: always
    dnf: 
     update_only: yes
     update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
     update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"








- hosts: web_servers
  become: true
  tasks:

  - name: install httpd and php package (CentOS)
    tags: apache,centos,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install httpd and php package (Ubuntu)
    tags: apache,centos,httpd
    apt:
      name:
        - appache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  - name: start httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: started
    when: ansible_distribution == "RedHat"

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
     when: ansible_distribution == "RedHat"
     register: varijabla

  - name: restart httpd (CentOS)
    tags: apache,centos,httpd
    service:
      name: httpd
      state: restarted
    when: varijabla.changed

  - name: copy deafult html file for site
    tags: apache,centos,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: owner
      mode: 0644








- hosts: db_servers
  become: true
  tasks: 
 
  - name: install mariadb (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"







- hosts: all
  become: true
  tasks: 

  # Dodano u boostrap.yml
  # - name: create simone user
  #   tags: always
  #   user:
  #     name: simone
  #     groups: root

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 kljuc"

  # - name: add sudoers file for simone
  #   tags: always
  #   copy:
  #     src: sudoer_simone
  #     dest: /ect/sudoers.d/simone
  #     owner: root
  #     group: root
  #     mode: 0440







- hosts: workstations
  become: true
  tasks: 
 
  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.2.4/terraform_1.2.4_windows_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest



